JWT:
  EXPIRE_MINUTE: 60
  ISSUER: "kim yang ja"
  SECRET: ${JWT_SECRET}

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 120MB
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENTID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: ${GOOGLE_REDIRECT_URL}
            scope:
              - email
              - profile
          kakao:
            clientId: ${KAKAO_CLIENTID}
            clientSecret: ${KAKAO_SECRET}
            redirectUri: ${KAKAO_REDIRECT_URL}
            authorizationGrantType: authorization_code
            clientName: kakao
            clientAuthenticationMethod: POST
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: info
        type: info

directory:
  root: "/handwriting_resources"
  image: "/handwriting_resources/image"