server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 120MB

  datasource:
    url: jdbc:mysql://handwriting.cyoyxp4jr4vl.ap-northeast-2.rds.amazonaws.com:3306/handwriting?serverTimezone=UTC&characterEncoding=UTF-8
    username: yandk97
    password: qwerasdf22
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update #스테이징과 운영 서버는 validate 또는 none
    show-sql: true
    properties:
      hiberate:
        format-sql: true

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: info
        type: info

directory:
  root: "/handwriting_resources"
  image: "/handwriting_resources/image"

url:
  default: "/api"
  image: "/api/image"

JWT:
  EXPIRE_MINUTE: 10
  ISSUER: "kim yang ja"
  SECRET: "12345789123456978946521321351531"

aws:
  s3:
    accessKey: "example key"
    secretKey: "example key"
    bucket: "example bucket"